"""
audit/cond_discipline_auditor.py — VIDHI false-positive measurement & ratchet.

Read-only probes over standard derivation states.  Reports raw ``cond()`` fires
vs post-scheduler ``enumerate_candidates()`` counts, grouped by adhyāya and
pattern bucket.

Usage:
    python audit/cond_discipline_auditor.py --status
    python audit/cond_discipline_auditor.py --write-report
"""
from __future__ import annotations

import argparse
import inspect
import re
import sys
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import sutras  # noqa: E402, F401

from engine.registry import SUTRA_REGISTRY  # noqa: E402
from engine.scheduler import enumerate_candidates  # noqa: E402
from engine.state import State, Term  # noqa: E402
from engine.sutra_type import SutraType  # noqa: E402
from phonology import mk  # noqa: E402

# Baselines pinned 2026-05-31 after phase pools + krt/samhita/tripadi migration
# + B2 subanta/kāraka gate scope (111 → 0 on bare BU dhātu probe).
VIDHI_FP_RAW_BASELINE = 0
VIDHI_FP_FILTERED_BASELINE = 0
# Tinanta tape-init probe (post Phase 5 tin_pratyaya chain gate).
TINANTA_INIT_RAW_BASELINE = 0

REPORT_PATH = ROOT / "docs" / "cond_discipline_audit.md"


@dataclass
class ProbeResult:
    name: str
    raw_vidhi: int = 0
    filtered_total: int = 0
    filtered_vidhi: int = 0
    by_adhyaya: Counter = field(default_factory=Counter)
    by_pattern: Counter = field(default_factory=Counter)


def bu_dhatu_probe() -> State:
    """Single-term BU dhātu — canonical false-positive probe."""
    return State(
        terms=[
            Term(
                kind="prakriti",
                varnas=[mk("B"), mk("U")],
                tags={"dhatu", "anga", "prakriti"},
                meta={"upadesha_slp1": "BU"},
            )
        ],
        phase="angakarya",
    )


def empty_probe() -> State:
    return State(phase="angakarya")


def bu_tinanta_initialized() -> State:
    """BU with tinanta tape-init tags (post Phase 2)."""
    from engine.tape_init.tinanta import build_tinanta_probe_state

    return build_tinanta_probe_state("BU", "laT", "kartari")


PROBE_BUILDERS: dict[str, Callable[[], State]] = {
    "bu_dhatu": bu_dhatu_probe,
    "empty": empty_probe,
    "bu_tinanta_init": bu_tinanta_initialized,
}


def _classify_cond_pattern(source_path: Path) -> str:
    try:
        text = source_path.read_text(encoding="utf-8")
    except OSError:
        return "unknown"
    m = re.search(r"def cond\(state.*?(?=\ndef |\nSUTRA|\Z)", text, re.S)
    body = m.group(0) if m else text
    if 'any("dhatu" in t.tags' in body or "any('dhatu' in t.tags" in body:
        return "any_dhatu"
    if "paribhasha_gates" in body and "return True" in body:
        return "paribhasha_gate_stub"
    if "krt_insertion_eligible" in body:
        return "krt_eligible"
    return "other"


def analyze_probe(state: State, name: str) -> ProbeResult:
    result = ProbeResult(name=name)
    filtered = enumerate_candidates(state)
    result.filtered_total = len(filtered)
    result.filtered_vidhi = sum(
        1 for sid in filtered
        if SUTRA_REGISTRY.get(sid)
        and SUTRA_REGISTRY[sid].sutra_type is SutraType.VIDHI
    )

    for sid, rec in SUTRA_REGISTRY.items():
        if rec.sutra_type is not SutraType.VIDHI:
            continue
        try:
            if not (rec.cond and rec.cond(state)):
                continue
        except Exception:
            continue
        result.raw_vidhi += 1
        adh = sid.split(".")[0]
        result.by_adhyaya[adh] += 1
        src = inspect.getsourcefile(rec.cond)
        bucket = _classify_cond_pattern(Path(src)) if src else "unknown"
        result.by_pattern[bucket] += 1

    return result


def run_all_probes() -> list[ProbeResult]:
    out: list[ProbeResult] = []
    for name, builder in PROBE_BUILDERS.items():
        try:
            state = builder()
        except Exception:
            continue
        out.append(analyze_probe(state, name))
    return out


def _render_report(probes: list[ProbeResult]) -> str:
    lines = [
        "# cond() discipline audit\n",
        "Auto-generated by `audit/cond_discipline_auditor.py`.\n",
        f"- **VIDHI_FP_RAW_BASELINE**: {VIDHI_FP_RAW_BASELINE}",
        f"- **VIDHI_FP_FILTERED_BASELINE**: {VIDHI_FP_FILTERED_BASELINE}",
        f"- **TINANTA_INIT_RAW_BASELINE**: {TINANTA_INIT_RAW_BASELINE}\n",
    ]
    for p in probes:
        lines.append(f"## Probe `{p.name}`\n")
        lines.append(f"| Metric | Count |")
        lines.append(f"|---|---:|")
        lines.append(f"| Raw VIDHI cond=True | {p.raw_vidhi} |")
        lines.append(f"| Filtered candidates (total) | {p.filtered_total} |")
        lines.append(f"| Filtered VIDHI | {p.filtered_vidhi} |")
        lines.append("")
        if p.by_pattern:
            lines.append("**Pattern buckets (raw VIDHI):**\n")
            for k, v in p.by_pattern.most_common():
                lines.append(f"- `{k}`: {v}")
            lines.append("")
        if p.by_adhyaya:
            lines.append("**By adhyāya (raw VIDHI):**\n")
            for k in sorted(p.by_adhyaya, key=lambda x: int(x)):
                lines.append(f"- adhyāya {k}: {p.by_adhyaya[k]}")
            lines.append("")
    return "\n".join(lines)


def cmd_status() -> int:
    probes = run_all_probes()
    bu = next((p for p in probes if p.name == "bu_dhatu"), probes[0] if probes else None)
    print("═" * 60)
    print("COND DISCIPLINE STATUS")
    print("═" * 60)
    if bu:
        print(f"BU probe raw VIDHI:       {bu.raw_vidhi}  (baseline {VIDHI_FP_RAW_BASELINE})")
        print(f"BU probe filtered VIDHI:  {bu.filtered_vidhi}  (baseline {VIDHI_FP_FILTERED_BASELINE})")
        print(f"BU probe filtered total:  {bu.filtered_total}")
        slack_raw = VIDHI_FP_RAW_BASELINE - bu.raw_vidhi
        slack_filt = VIDHI_FP_FILTERED_BASELINE - bu.filtered_vidhi
        print(f"slack raw:                {slack_raw:+d}")
        print(f"slack filtered:           {slack_filt:+d}")
    print("")
    for p in probes:
        print(f"  [{p.name}] raw={p.raw_vidhi} filtered_vidhi={p.filtered_vidhi} total={p.filtered_total}")
    print("═" * 60)
    return 0


def cmd_write_report() -> int:
    probes = run_all_probes()
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(_render_report(probes), encoding="utf-8")
    print(f"wrote {REPORT_PATH}")
    return cmd_status()


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="VIDHI cond() false-positive auditor.")
    p.add_argument("--status", action="store_true", help="Print current counts vs baselines.")
    p.add_argument("--write-report", action="store_true", help="Write docs/cond_discipline_audit.md.")
    args = p.parse_args(argv)
    if args.write_report:
        return cmd_write_report()
    return cmd_status()


if __name__ == "__main__":
    raise SystemExit(main())
