"""
tools/conflict_ledger.py — collect every loop≠Vidyut cell from the tri_compare sweeps (.audit/tri_<pada>_<lakara>_<gana>.out)
into docs/CONFLICT_CELLS.md: one row per (root, gaṇa, lakāra, pada), with the first differing cell, grouped by gaṇa.

Not a verdict: a cell is listed when our engine's form is not among Vidyut's. Whether Vidyut or we are right is the work of the
dedicated conflict session (docs/CONFLICTS.md holds the sūtra-level questions for the expert).

    python3 -m tools.conflict_ledger
"""
from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_PAT = re.compile(r"^(?P<root>\S+) (?P<cell>\d-\d)\s+recipe (?P<rec>\S+)\s+loop (?P<loop>\S+)\s+vidyut (?P<vid>.*?)\s+<--\s*(?P<flags>.*)$")


def main() -> int:
    rows: dict[tuple, dict] = {}
    for f in sorted((_ROOT / ".audit").glob("tri_*_*_*.out")):
        pada, lakara, gana = f.stem.split("_")[1:4]
        for line in f.read_text(encoding="utf-8", errors="ignore").splitlines():
            m = _PAT.match(line)
            if not m or "loop≠V" not in m["flags"]:
                continue
            key = (int(gana), m["root"], lakara, pada)
            r = rows.setdefault(key, {"n": 0, "first": m})
            r["n"] += 1
    by_gana: dict[int, list] = defaultdict(list)
    for (g, root, la, pada), r in sorted(rows.items()):
        by_gana[g].append((root, la, pada, r))
    out = ["# loop ≠ Vidyut cells (generated by tools/conflict_ledger.py — do not edit)", "",
           f"{len(rows)} (root, lakāra, pada) groups. A group is listed when our form is not among Vidyut's; "
           "the recipe column is our older pipeline. Verdicts live in docs/CONFLICTS.md.", ""]
    for g in sorted(by_gana):
        out += [f"## gaṇa {g}", "", "| root | lakāra | pada | cells | e.g. | ours (loop) | Vidyut | recipe |", "|---|---|---|---|---|---|---|---|"]
        for root, la, pada, r in by_gana[g]:
            m = r["first"]
            out.append(f"| {root} | {la} | {pada} | {r['n']} | {m['cell']} | {m['loop']} | {m['vid']} | {m['rec']} |")
        out.append("")
    (_ROOT / "docs" / "CONFLICT_CELLS.md").write_text("\n".join(out), encoding="utf-8")
    print(f"{len(rows)} groups -> docs/CONFLICT_CELLS.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
