"""
tools/nisedha_review.py — the निषेध worklist, for a scholar to settle.

`make lint` reports 87 sūtras whose padaccheda carries the standalone word न —
a निषेध — typed VIDHI with no declared block. 6.1.104 नादिचि was one of them,
and रामौ derived for the wrong reason until it was fixed.

The other 86 cannot be fixed the same way by tooling, and this file exists to
say why. Measured 2026-09-15:

  * **none of the 87 ever fires** — not one is invoked anywhere in the suite,
    so this is not a live mistyping but 87 unimplemented rules wearing the
    wrong label;
  * the reference corpus names a single VIDHI in the anuvṛtti chain for
    exactly **one** of them. For the rest, *what each negates* is not in the
    data we hold.

So the tool proposes and never writes. It assembles, for each sūtra, the text,
padaccheda, adhikāra, anuvṛtti chain, the Kāśikā udāharaṇa, and the
**immediately preceding sūtra** — which is very often the utsarga a न-rule
negates, and is offered as a proposal, not a finding. A scholar confirms the
target; `blocks_sutra_ids` is written only then.

    python3 -m tools.nisedha_review          # writes docs/NISEDHA_REVIEW.md
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

MD_PATH = _ROOT / "docs" / "NISEDHA_REVIEW.md"
JSON_PATH = _ROOT / "sig" / "nisedha_review.json"


def _ref(sutra_id: str) -> dict[str, Any]:
    path = _ROOT / "sutra_ref_out" / (sutra_id.replace(".", "_") + ".json")
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}


def _kashika(record: dict[str, Any]) -> str:
    from tools.cite_sutras import _example

    for source, text in map(_example, record.get("examples") or []):
        if source.lower().startswith("kashika") and text:
            return text
    return ""


def collect() -> list[dict[str, Any]]:
    import sutras  # noqa: F401
    from engine import SUTRA_REGISTRY
    from engine.coverage import load_ledger
    from tools.sutra_lint import lint

    ledger = load_ledger() or {}
    invoked = set(ledger.get("invoked", ()))
    rows: list[dict[str, Any]] = []
    for finding in lint()["findings"]["nisedha-as-vidhi"]:
        sid = finding.split()[0]
        record = _ref(sid)
        inheritance = record.get("inheritance") or {}
        anuvritta = [a["sutra"] for a in (inheritance.get("anuvritta") or [])]
        rows.append({
            "sutra_id": sid,
            "text_dev": (record.get("text") or {}).get("dev", ""),
            "padaccheda_dev": ((record.get("text") or {}).get("padaccheda") or {}).get("dev", ""),
            "adhikara": inheritance.get("adhikara"),
            "anuvritta": anuvritta,
            "anuvritta_vidhi": [
                a for a in anuvritta
                if a in SUTRA_REGISTRY and SUTRA_REGISTRY[a].sutra_type.name == "VIDHI"
            ],
            "previous_sutra": (record.get("downstream") or {}).get("previous_sutra"),
            "kashika": _kashika(record),
            "fires_anywhere": sid in invoked,
        })
    return rows


def main() -> int:
    rows = collect()
    JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    JSON_PATH.write_text(json.dumps({"count": len(rows), "nisedhas": rows},
                                    ensure_ascii=False, indent=2), encoding="utf-8")

    firing = [r for r in rows if r["fires_anywhere"]]
    lines = [
        "# निषेध review — what does each of these negate?",
        "",
        f"*Generated by `python3 -m tools.nisedha_review`. {len(rows)} sūtras, "
        f"{len(firing)} of them currently firing.*",
        "",
        "Each row is a sūtra whose **padaccheda carries the standalone word न** and",
        "which is typed VIDHI with no declared block. CONSTITUTION Art. 15 needs the",
        "relation declared; the data we hold does not say what most of these negate,",
        "so the *proposed target* below is the immediately preceding sūtra — a",
        "regularity, not a citation. **Confirm or correct it before it is written.**",
        "",
        "When a row is settled, the sūtra is retyped `PRATISHEDHA` with",
        "`blocks_sutra_ids=(…)`, exactly as 6.1.104 नादिचि was on 2026-09-15.",
        "",
        "| सूत्र | पाठ | पदच्छेद | adhikāra | proposed target | Kāśikā udāharaṇa | fires? |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| `{row['sutra_id']}` | {row['text_dev']} | {row['padaccheda_dev']} "
            f"| {row['adhikara'] or '—'} "
            f"| {row['anuvritta_vidhi'][0] if row['anuvritta_vidhi'] else (row['previous_sutra'] or '—')} "
            f"| {row['kashika'][:48] or '—'} "
            f"| {'yes' if row['fires_anywhere'] else 'no'} |"
        )
    lines += [
        "",
        "## Why this is a review and not a sweep",
        "",
        "None of these fires today, so nothing is currently deciding a derivation on",
        "a wrong basis — they are unimplemented rules with the wrong label. Declaring",
        "86 block targets from a regularity would put 86 unsourced claims into the",
        "registry, which Art. 14 forbids and Art. 15 would then enforce as if true.",
        "",
        "The lint keeps two counts apart for this reason: a निषेध typed VIDHI that",
        "**fires** is an error and must stay at zero; one that does not is backlog.",
        "",
    ]
    MD_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  {len(rows)} निषेधs · {len(firing)} firing")
    print(f"  {MD_PATH.relative_to(_ROOT)}")
    print(f"  {JSON_PATH.relative_to(_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
