"""make status → docs/STATUS.md (generated; never hand-edit). Each line cites source + mtime."""
import json, time
from pathlib import Path
R = Path(__file__).resolve().parent.parent
def ts(p): return time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime(p.stat().st_mtime))
c, s = R/"sig/coverage.json", R/"sig/sutra_class.json"
cov, cls = json.loads(c.read_text()), json.loads(s.read_text())
conf = sum(r["status"].startswith("confident") for r in cls["rows"])
g = sorted((R/"bench/report").glob("2*.json"))
out = ["# STATUS (generated by `make status`; do not edit)", "",
       f"- implemented {cov['implemented']}/{cov['total']} ({cov['coverage_pct']}%) — `sig/coverage.json` @ {ts(c)}",
       f"- confident {conf} — `sig/sutra_class.json` @ {ts(s)}",
       f"- latest bench file: `{g[-1].name}` @ {ts(g[-1])}" if g else "- no bench report"]
(R/"docs/STATUS.md").write_text("\n".join(out) + "\n"); print("\n".join(out))
