"""
tools/sutra_changes.py — what happened to each sūtra file, for the integrity audit.

    python3 -m tools.sutra_changes --since 3212eba9~1            # markdown to stdout
    python3 -m tools.sutra_changes --since <rev> --write         # docs/SUTRA_CHANGES.md

For every commit after ``--since`` that touches ``sutras/``, one row per file: the sūtra id, and *what kind*
of change it was, decided by comparing the old and new syntax trees — not by the commit message:

  NEW            file did not exist
  LOGIC          cond / act / a helper changed (behaviour can differ)
  DECLARATION    SutraRecord keywords changed (type, apavada_of, blocks, vibhasha_default, exempt …)
  CITATION/DOC   docstring or comments only (no code difference)
  REFORMAT       identical syntax tree

Declarations and logic are listed with the changed names, so an auditor sees what to open.
"""
from __future__ import annotations

import argparse
import ast
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def git(*args: str) -> str:
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True).stdout


def _split(src: str):
    """(docstring-stripped code dump, record kwargs dict) for a sūtra file."""
    tree = ast.parse(src)
    if tree.body and isinstance(tree.body[0], ast.Expr) and isinstance(getattr(tree.body[0], "value", None), ast.Constant):
        tree.body = tree.body[1:]
    kw: dict[str, str] = {}
    code_nodes = []
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(getattr(t, "id", "") == "SUTRA" for t in node.targets) \
                and isinstance(node.value, ast.Call):
            for k in node.value.keywords:
                if k.arg and k.arg not in ("why_dev", "text_slp1", "text_dev", "samagra_slp1", "samagra_dev", "padaccheda_dev", "anuvritti_from"):
                    kw[k.arg] = ast.dump(k.value)
                elif k.arg == "why_dev":
                    kw["why_dev"] = "(text)"
        else:
            code_nodes.append(node)
    funcs = {}
    for node in code_nodes:
        name = getattr(node, "name", None) or ast.dump(node)[:60]
        funcs[name] = ast.dump(node)
    return funcs, kw


def classify(old: str | None, new: str) -> tuple[str, str]:
    if old is None:
        return "NEW", ""
    try:
        of, ok = _split(old)
        nf, nk = _split(new)
    except SyntaxError:
        return "LOGIC", "(unparseable)"
    changed_funcs = sorted({k for k in set(of) | set(nf) if of.get(k) != nf.get(k)})
    changed_kw = sorted({k for k in set(ok) | set(nk) if ok.get(k) != nk.get(k) and k != "why_dev"})
    if changed_funcs:
        return "LOGIC", ", ".join(n for n in changed_funcs if not n.startswith("Import"))[:120] or "imports"
    if changed_kw:
        return "DECLARATION", ", ".join(changed_kw)
    if old.strip() == new.strip():
        return "REFORMAT", ""
    return "CITATION/DOC", ""


def report(since: str) -> str:
    revs = git("log", "--reverse", "--format=%h|%s", f"{since}..HEAD", "--", "sutras/").strip().splitlines()
    out = [f"# Sūtra changes since `{since}` (generated by `tools.sutra_changes` — AST comparison, not commit messages)", ""]
    for line in revs:
        rev, subject = line.split("|", 1)
        files = [f for f in git("diff-tree", "--no-commit-id", "--name-status", "-r", rev, "--", "sutras/").splitlines() if f]
        rows = []
        for f in files:
            status, path = f.split("\t")[0], f.split("\t")[-1]
            m = re.search(r"sutra_(\d+)_(\d+)_(\d+)\.py$", path)
            if not m:
                continue
            sid = ".".join(m.groups())
            old = git("show", f"{rev}~1:{path}") if status != "A" else None
            new = git("show", f"{rev}:{path}")
            if status == "D":
                rows.append((sid, "DELETED", ""))
                continue
            kind, detail = classify(old if old else None, new)
            rows.append((sid, kind, detail))
        if not rows:
            continue
        out += [f"## `{rev}` — {subject}", "", "| sūtra | change | what |", "|---|---|---|"]
        key = lambda r: tuple(int(x) for x in r[0].split("."))
        out += [f"| {sid} | {kind} | {detail} |" for sid, kind, detail in sorted(rows, key=key)]
        out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--since", required=True)
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    text = report(a.since)
    if a.write:
        (ROOT / "docs" / "SUTRA_CHANGES.md").write_text(text, encoding="utf-8")
        print(f"wrote docs/SUTRA_CHANGES.md ({text.count(chr(10))} lines)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
